services:
  - type: web
    name: tg-osint-api
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TGDATA_PARQUET
        value: /opt/render/project/src/data/tgdata.parquet
      - key: BOT_TOKEN
        value: 8830055380:AAGdtxtpmRSp--Eoiph98TEa617IpFuS39s
      - key: BOT_USERNAME
        value: cloud_computings_bot
      - key: DEVELOPER
        value: "@OSINT_CLONER"
      - key: CHANNEL
        value: "@premiumscriptsbackup"
      - key: DUCKDB_MEM
        value: "400MB"
      - key: MASTER_KEY
        generateValue: true
    healthCheckPath: /health
